[build-system]
requires = ["maturin>=1.10.2,<2.0"]
build-backend = "maturin"

[project]
name = "rustkit_learning"
version = "0.1.0"
description = "A modern rust implemented and type aware replacement for scikit-learning"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "bokeh>=3.8.1",
    "numpy>=2.3.5",
]

[tool.uv]
cache-keys = [
  { file = "pyproject.toml" },
  { file = "Cargo.toml" },
  { file = "**.rs" }
]
