[package]
name = "rustkit_learning_backend"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
ndarray = "0.17.1"
pyo3 = { version = "0.27.1", features = ["extension-module"]}

[dev-dependencies]
pyo3-stub-gen = "0.17.2"